---
# This playbook sets up whole stack.
- hosts: tag_Name_MSR_test_Instance_1
  remote_user: ubuntu # Remote user
  become: yes
  tasks:
    - name: Clone a private repository into ~/docker-ansible.
      git:
        repo: 'https://github.com/venkat09docs/docker-ansible.git'
        version: master
        dest: /opt/docker-ansible
    - name: This command will change the working directory to somedi
      shell: /opt/docker-ansible/docker-build.sh >> output.txt
      args:
        chdir: /opt/docker-ansible/  
